name: triage-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - scikit-learn
      - fastapi
      - uvicorn
      - faker
      - joblib
      - pydantic